### ISSUE TITLE
ipbc miner ppc64le support?

### ISSUE THREAD

**Issue by night2417** [ipbc-dev/bittube-miner#1]
I have a question about the new ipbc miner. If you connect to the site https://github.com/nioroso-x3/xmr-stak …, you can also support linux ppc64le IBM Power8. Will IPBC miners be supported? Or is it impossible?

**Comment by mrosset** [comment]
it's might be possible, I have access to a power8 machine will try to do some porting. will report back

**Comment by night2417** [comment]
Thank you. I look forward to your reporting. mrosset

**Comment by mrosset** [comment]
so far there are issues with aes hardware support, an cpuid support. As far as I can see it's not an easy fix at this stage. I'm going to keep picking at it though see what I can do.

**Comment by mrosset** [comment]
@night2417 can you build https://github.com/nioroso-x3/xmr-stak on your power8 meantime. it supports monerov7 and friends . but not the new ipbc lite algo. when I have more time I'll try figure out how to get the two merged together some how.

you'll need gcc-7.3 and cmake 3 for to build that fork. also you have to LD_LIBRARY_PATH to the libstdc++ lib diretory if you  build gcc manually. my power8 distro uses gcc 4.8 dunno about yours.

Maybe we can get @nioroso-x3 to add the new ipbc lite algo to his fork.

**Comment by ipbc-dev** [comment]
CPU mining is no longer profitable with the new algorithm and as such there're no plans to extend the support for other CPU architectures.
