### ISSUE TITLE
NVIDIA Insufficient driver! backend NVIDIA disabled.

### ISSUE THREAD

**Issue by un1t** [ipbc-dev/bittube-miner#12]
I compiled source code on Ubuntu 16.04 (cuda-9.1), and it said:

> WARNING: NVIDIA Insufficient driver!
> [2018-06-01 09:09:12] : WARNING: backend NVIDIA disabled.

Also I tried docker, there was the same error.

ccminer with cryptonight algorithm works fine on this machine

**Comment by ipbc-dev** [comment]
new cuda release available
