### ISSUE TITLE
Httpd doesnt work right after compile

### ISSUE THREAD

**Issue by Neoony** [ipbc-dev/bittube-miner#15]
When I compile bittube miner, httpd doesnt work no matter what. [things seem to compile without any errors]
But, when I access httpd, it only says that "something isnt right"

If I compile original xmr-stak, there is no issue.

But it works fine if I download bittube-miner from releases.

**Comment by Neoony** [comment]
Aha!
This is maybe related to non-expert mode using bit.tube/startmining over httpd?

While bit.tube/startmining works, it shows up: "This doesn't seem to be right." if you access your local ip on the port 8282.

Maybe something to do with that?

**Comment by ipbc-dev** [comment]
working on it, some major miner changes are coming.

**Comment by Neoony** [comment]
looks like this is pretty much ok if I open http://yourip:port/api.json

**Comment by ipbc-dev** [comment]
This has been fixed in the latest release and now correctly redirects http://localhost:port to the hashrate report.
