### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by night2417** [ipbc-dev/bittube-miner#17]
[root@alice03 bittube-miner-2.0.0.0]# make install
[ 23%] Built target bittube-miner-c
[ 92%] Built target bittube-miner-backend
[ 96%] Building CXX object CMakeFiles/bittube-miner.dir/xmrstak/cli/cli-miner.cpp.o
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp: In function ‘bool check_expert_mode(bool*, bool*)’:
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp:917:32: warning: unknown escape sequence: '\)'
  std::regex expertParamPattern(".*\(expert_mode\)\.*[:]\.*(true|false)\.*");
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp:917:32: warning: unknown escape sequence: '\.'
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp:917:32: warning: unknown escape sequence: '\.'
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp:917:32: warning: unknown escape sequence: '\.'
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp: In function ‘void restart_miner(bool, bool)’:
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp:979:2: error: ‘httpd’ has not been declared
  httpd::cls();
  ^~~~~
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp: In function ‘int main(int, char**)’:
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp:1036:3: error: ‘httpd’ has not been declared
   httpd::miningState(true);
   ^~~~~
/opt/bittube-miner-2.0.0.0/xmrstak/cli/cli-miner.cpp:1053:5: error: ‘httpd’ has not been declared
     httpd::miningState(true);
     ^~~~~
make[2]: *** [CMakeFiles/bittube-miner.dir/xmrstak/cli/cli-miner.cpp.o] Error 1
make[1]: *** [CMakeFiles/bittube-miner.dir/all] Error 2
make: *** [all] Error 2
[root@alice03 bittube-miner-2.0.0.0]# ls

**Comment by ipbc-dev** [comment]
Building without httpd has been fixed in master.
