### ISSUE TITLE
Compile with httpd support

### ISSUE THREAD

**Issue by meyerbro** [ipbc-dev/bittube-miner#2]
Tried enabling port for that and said it wasn't compiled with this support...

Can you provide a httpd compatible version?

Thanks

**Comment by savicsava** [comment]
Hi team. Great work so far. Can you please elaborate why didn't you enable httpd support for web server in binaries in miner. I use that (and many others) for JJScript that  is used for Vegas so we can monitor drop in Hashrate. Script is listening to that port, and if hashrate drops, then drivers and miner are restarted. This is common feature of XMR stak, no reason to disable it...

**Comment by nsummy** [comment]
Gents, I followed these instructions which worked perfectly:  https://github.com/ipbc-dev/ipbc-miner/blob/master/doc/compile_Windows.md

I would uploaded the compiled version I made for you guys but I don't think it would help as I only compiled it for Nvidia and CPU.  If you really want though reply and I can add AMD support and send you the link to the files

**Comment by ipbc-dev** [comment]
The release binaries have now been compiled with httpd, ssl and hwloc support.
