### ISSUE TITLE
nvidia compatibility 

### ISSUE THREAD

**Issue by Leonmanveli** [ipbc-dev/bittube-miner#21]
when there will actually be a working bittube miner for nvidia? :(

**Comment by ipbc-dev** [comment]
check the latest release, cuda support has been added, today.

**Comment by psychocrypt** [comment]
@ipbc-dev A link within the commit or a PR with a link to the source of the cuda code would be a good practice.

**Comment by ipbc-dev** [comment]
@psychocrypt sorry my bad, have not thinked about it, will add.
