### ISSUE TITLE
Nvidia Architeture 21 missing

### ISSUE THREAD

**Issue by denisbim** [ipbc-dev/bittube-miner#3]
WARNING: NVIDIA GPU 0: miner not compiled for the gpu architecture 21.

**Comment by nsummy** [comment]
Are you compiling it yourself or are you using one of the precompiled versions?  What kind of cards and OS are you using?

**Comment by denisbim** [comment]
I'm using precompiled version, the last one, NVIDIA 630M on Windows 10

**Comment by nsummy** [comment]
That card doesn't support Cuda 9.  They don't say what version they used to compile the release, but its probably 9.  I compiled it for Cuda 8 if you want to try it.  It should work.  
[ipbcminer 1.1.2 cuda 8.zip](https://github.com/ipbc-dev/ipbc-miner/files/1920339/ipbcminer.1.1.2.cuda.8.zip)

**Comment by denisbim** [comment]
same error, thank you for trying to help.

**Comment by ipbc-dev** [comment]
The windows binaries are now compiled against both CUDA version 8.0 and 9.1.

**Comment by ipbc-dev** [comment]
I'm closing this since there're no new replies, if this is still an issue please let me know.
