### ISSUE TITLE
how to miner for linux?

### ISSUE THREAD

**Issue by sgly2002** [ipbc-dev/bittube-miner#4]
how to miner for linux?

**Comment by ipbc-dev** [comment]
You can either try the latest build for 64bit Ubuntu 17.10 from [Releases](https://github.com/ipbc-dev/ipbc-miner/releases) or follow the instructions to [Compile ipbc-miner for Linux](https://github.com/ipbc-dev/ipbc-miner/blob/master/doc/compile_Linux.md).
