### ISSUE TITLE
Can't run on Ubuntu 16.04

### ISSUE THREAD

**Issue by sbash** [ipbc-dev/bittube-miner#7]
./ipbc-miner
./ipbc-miner: error while loading shared libraries: libmicrohttpd.so.12: cannot open shared object file: No such file or directory

The library is installed...  Can I disable the miner from using it?  (I don't want or need it)

**Comment by babyrig** [comment]
Same problem here with the new and old binaries - Ubuntu 16.04
The library is installed here too and I can't compile either

**Comment by EicHub** [comment]
same problem at ubuntu 16.04 server

**Comment by un1t** [comment]
same problem Ubuntu 16.0 Desktop

**Comment by ipbc-dev** [comment]
thank you!

**Comment by jcdomingos** [comment]
apt install libmicrohttpd-dev
