### ISSUE TITLE
Miner execution in pause

### ISSUE THREAD

**Issue by Neoony** [ipbc-dev/bittube-miner#9]
1.1.6 issue
I have been trying to set up the BitTube miner first time, but got a bit of a problem.

When I start the miner first time:
![bittube-miner_2018-05-26_01-55-52](https://user-images.githubusercontent.com/24975075/40570593-a52f07c0-608c-11e8-959e-77fab216554d.png)

And never continues.
Starting again:
![bittube-miner_2018-05-26_02-07-50](https://user-images.githubusercontent.com/24975075/40570606-bba0ec3a-608c-11e8-8c27-32672c76a143.png)

When I go to the url, it will just show the download link and something thats loading in the bottom of the page...infinitely.
![2018-05-26_02-01-40](https://user-images.githubusercontent.com/24975075/40570611-c0f5368c-608c-11e8-8b93-dd0be41ed7a2.gif)

I tried different browsers and also connecting over tor browser. It never loads up.

Am I supposed to go to the url and somehow unpause it? Or am I missing something?

I can run the original xmr-stak just fine.

Not sure if its a bug or Iam supposed to do something.

Note: I just tried the 1.1.5 version and it works no problem.

**Comment by Neoony** [comment]
Fixed in https://github.com/ipbc-dev/bittube-miner/releases/tag/1.1.7

**Comment by VandeurenGlenn** [comment]
Same here with the latest version.
